cnn0_units: 128
cnn1_units: 256
lstm0_units: 30
lstm1_units: 20
lstm2_units: 10
lag: 1
points_per_call: 32
regularizers_l2: 0.2
recurrent_dropout_rate: 0.2
activation: 'relu'
optimizer: 'adam'
epochs: 250
points_to_predict: 288
start_data: "2023-11-28 21:00:00"
target_date_str: "2023-11-28 21:00:00"
